[package]
name = "smol_str"
version = "0.2.2"
description = "small-string optimized string type with O(1) clone"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-analyzer/smol_str"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2021"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[dependencies]
serde = { version = "1.0", optional = true, default-features = false }
arbitrary = { version = "1.3", optional = true }

[dev-dependencies]
proptest = "1.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["std"]
std = ["serde?/std"]
serde = ["dep:serde"]
