name: CI
on:
  pull_request:
  push:
    branches:
    - master
    - staging
    - trying

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache: false

    - run: rustc ./.github/ci.rs && ./ci
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
